routes/web.php
<?php

use App\Http\Controllers\ClassRoomCodeController;
use App\Http\Controllers\ClassRoomController;
use App\Http\Controllers\ClassRoomPostController;
use App\Http\Controllers\ClassRoomResourceController;
use App\Http\Controllers\ClassRoomScoreController;
use App\Http\Controllers\ClassRoomStudentController;
use App\Http\Controllers\ClassRoomTaskController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'dashboard');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::view('class-rooms/create', 'class-rooms.create')->name('class-rooms.create');
    Route::post('class-rooms', [ClassRoomController::class, 'store'])->name('class-rooms.store');
    Route::get('class-rooms/{classRoomSlug}', [ClassRoomController::class, 'detail'])->name('class-rooms.detail');
    Route::get('class-rooms/{classRoomSlug}/edit', [ClassRoomController::class, 'edit'])->name('class-rooms.edit');
    Route::post('class-rooms/{classRoomSlug}', [ClassRoomController::class, 'update'])->name('class-rooms.update');
    Route::delete('class-rooms/{classRoomSlug}/archive', [ClassRoomController::class, 'archive'])->name('class-rooms.archive');

    Route::get('archived-class-rooms', [ClassRoomController::class, 'archived'])->name('class-rooms.archived');
    Route::put('archived-class-rooms/{classRoomSlug}/restore', [ClassRoomController::class, 'restore'])->name('class-rooms.restore');

    Route::post('class-room-code/generate', [ClassRoomCodeController::class, 'generate'])->name('class-room-code.generate');
    Route::post('class-room-code/delete', [ClassRoomCodeController::class, 'delete'])->name('class-room-code.delete');
    Route::post('class-room-code/join', [ClassRoomCodeController::class, 'join'])->name('class-room-code.join');

    Route::get('class-rooms/{classRoomSlug}/students', [ClassRoomStudentController::class, 'index'])->name('class-rooms.students.index');
    Route::post('class-rooms/{classRoomSlug}/students', [ClassRoomStudentController::class, 'invite'])->name('class-rooms.students.invite');
    Route::delete('class-rooms/{classRoomSlug}/students', [ClassRoomStudentController::class, 'detach'])->name('class-rooms.students.detach');
    Route::get('class-rooms/{classRoomSlug}/students/{encryptedId}', [ClassRoomStudentController::class, 'detail'])->name('class-rooms.students.detail');

    Route::get('class-rooms/{classRoomSlug}/posts', [ClassRoomPostController::class, 'index'])->name('class-rooms.posts.index');
    Route::get('class-rooms/{classRoomSlug}/posts/create', [ClassRoomPostController::class, 'create'])->name('class-rooms.posts.create');
    Route::post('class-rooms/{classRoomSlug}/posts', [ClassRoomPostController::class, 'store'])->name('class-rooms.posts.store');
    Route::get('class-rooms/{classRoomSlug}/posts/{postSlug}', [ClassRoomPostController::class, 'detail'])->name('class-rooms.posts.detail');
    Route::get('class-rooms/{classRoomSlug}/posts/{postSlug}/edit', [ClassRoomPostController::class, 'edit'])->name('class-rooms.posts.edit');
    Route::post('class-rooms/{classRoomSlug}/posts/{postSlug}', [ClassRoomPostController::class, 'update'])->name('class-rooms.posts.update');
    Route::delete('class-rooms/{classRoomSlug}/posts/{postSlug}', [ClassRoomPostController::class, 'delete'])->name('class-rooms.posts.delete');

    Route::get('class-rooms/{classRoomSlug}/resources', [ClassRoomResourceController::class, 'index'])->name('class-rooms.resources.index');
    Route::post('class-rooms/{classRoomSlug}/resources', [ClassRoomResourceController::class, 'create'])->name('class-rooms.resources.create');
    Route::get('class-rooms/{classRoomSlug}/resources/{resourceSlug}', [ClassRoomResourceController::class, 'detail'])->name('class-rooms.resources.detail');
    Route::get('class-rooms/{classRoomSlug}/resources/{resourceSlug}/full-screen', [ClassRoomResourceController::class, 'fullScreen'])->name('class-rooms.resources.full-screen');
    Route::delete('class-rooms/{classRoomSlug}/resources/{resourceSlug}', [ClassRoomResourceController::class, 'delete'])->name('class-rooms.resources.delete');

    Route::get('class-rooms/{classRoomSlug}/tasks', [ClassRoomTaskController::class, 'index'])->name('class-rooms.tasks.index');
    Route::get('class-rooms/{classRoomSlug}/tasks/create', [ClassRoomTaskController::class, 'create'])->name('class-rooms.tasks.create');
    Route::post('class-rooms/{classRoomSlug}/tasks', [ClassRoomTaskController::class, 'store'])->name('class-rooms.tasks.store');
    Route::get('class-rooms/{classRoomSlug}/tasks/{taskSlug}', [ClassRoomTaskController::class, 'detail'])->name('class-rooms.tasks.detail');
    Route::get('class-rooms/{classRoomSlug}/tasks/{taskSlug}/edit', [ClassRoomTaskController::class, 'edit'])->name('class-rooms.tasks.edit');
    Route::post('class-rooms/{classRoomSlug}/tasks/{taskSlug}/update', [ClassRoomTaskController::class, 'update'])->name('class-rooms.tasks.update');
    Route::delete('class-rooms/{classRoomSlug}/tasks/{taskSlug}', [ClassRoomTaskController::class, 'delete'])->name('class-rooms.tasks.delete');

    Route::post('class-rooms/{classRoomSlug}/tasks/{taskSlug}/submit', [ClassRoomTaskController::class, 'submit'])->name('class-rooms.tasks.submit');
    Route::post('class-rooms/{classRoomSlug}/tasks/{taskSlug}/score', [ClassRoomTaskController::class, 'score'])->name('class-rooms.tasks.score');

    Route::get('class-rooms/{classRoomSlug}/score', [ClassRoomScoreController::class, 'index'])->name('class-rooms.score.index');

    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::post('profile', [ProfileController::class, 'update'])->name('profile.update');
});

Route::get('retrive-storage/{encryptedPath}', function ($encryptedPath) {
    $path = decrypt($encryptedPath);
    if (!Storage::exists($path)) {
        return null;
    }

    $content = Storage::get($path);

    return Response::make($content, 200, [
        'Content-Type' => Storage::mimeType($path),
        'Content-Disposition' => 'inline; filename="'. basename($path) .'"'
    ]);
})->name('retrive-storage');

Route::get('download-storage/{encryptedPath}', function ($encryptedPath) {
    return Storage::download(decrypt($encryptedPath));
})->name('download-storage');

app/Models/ClassRoom.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ClassRoom extends Model
{
	const COVER_PATH = 'class_rooms/covers';

	protected $table = 'class_rooms';
	protected $fillable = [
		'teacher_id',
		'cover_path',
		'name',
		'slug',
		'description',
		'code',
		'code_expired_at',
		'archived_at'
	];
	protected $casts = [
		'code_expired_at' => 'datetime'
	];

	public function teacher()
	{
		return $this->belongsTo(User::class, 'teacher_id', 'id')
			->where('role', User::ROLE_TEACHER);
	}

	public function students()
	{
		return $this->belongsToMany(User::class, 'class_room_student', 'class_room_id', 'student_id')
			->withPivot(['average_score']);
	}

	public function posts()
	{
		return $this->hasMany(Post::class, 'class_room_id');
	}

	public function resources()
	{
		return $this->hasMany(Resources::class, 'class_room_id');
	}

	public function tasks()
	{
		return $this->hasMany(Task::class, 'class_room_id');
	}

	public function scopeMine($query, $user)
	{
		if ($user->role == User::ROLE_TEACHER) {
			$query->where('teacher_id', $user->id);
		} else {
			$query->whereHas('students', function ($students) use ($user) {
				$students->where('student_id', $user->id);
			});
		}

		return $query;
	}

	public function scopeSlug($query, $role)
	{
		return $query->where('slug', $role);
	}

	public function getCoverAttribute()
	{
		return route('retrive-storage', encrypt($this->cover_path));
	}
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $table = 'posts';
	protected $fillable = [
		'class_room_id',
		'title',
		'slug',
		'content',
		'published_at'
	];
	protected $casts = [
		'published_at' => 'datetime'
	];

	public function classRoom()
	{
		return $this->belongsTo(ClassRoom::class, 'class_room_id');
	}

	public function getContentPreviewAttribute()
	{
		return substr(strip_tags($this->content), 0, 100) . '...';
	}
}

app/Http/Controllers/ClassRoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\ClassRoom;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ClassRoomController extends Controller
{
	public function store(Request $request)
	{
		$request->validate([
			'cover' => 'required|image',
			'name' => 'required',
			'slug' => 'required|unique:class_rooms,slug',
			'description' => 'required'
		]);

		$classRoom = new ClassRoom();
		$classRoom->fill($request->only(['name', 'slug', 'description']));
		$classRoom->teacher_id = auth()->id();
		$classRoom->cover_path = $request->file('cover')->store(ClassRoom::COVER_PATH);
		$classRoom->save();

		return redirect()->route('class-rooms.detail', $classRoom->slug);
	}

	public function detail(string $slug)
	{
		return view('class-rooms.detail', [
			'classRoom' => ClassRoom::mine(auth()->user())
				->where('slug', $slug)
				->firstOrFail()
		]);
	}

	public function edit(string $slug)
	{
		return view('class-rooms.edit', [
			'classRoom' => ClassRoom::mine(auth()->user())
				->where('teacher_id', auth()->id())
				->where('slug', $slug)->firstOrFail()
		]);
	}

	public function update(Request $request, string $slug)
	{
		$classRoom = ClassRoom::mine(auth()->user())
			->where('teacher_id', auth()->id())
			->where('slug', $slug)->firstOrFail();

		$request->validate([
			'cover' => 'nullable|image',
			'name' => 'required',
			'slug' => 'required|unique:class_rooms,slug,'.$classRoom->id,
			'description' => 'nullable'
		]);

		$classRoom->fill($request->only(['name', 'slug', 'description']));
		if ($request->file('cover')) {
			Storage::delete($classRoom->cover_path);
			$classRoom->cover_path = $request->file('cover')->store(ClassRoom::COVER_PATH);
		}

		$classRoom->save();

		return redirect()->route('class-rooms.detail', $classRoom->slug);
	}

	public function archive(string $slug)
	{
		ClassRoom::mine(auth()->user())->where('teacher_id', auth()->id())->where('slug', $slug)->update([
			'archived_at' => now()
		]);

		return redirect()->route('dashboard');
	}

	public function archived()
	{
		return view('class-rooms.archived', [
			'classRooms' => ClassRoom::mine(auth()->user())
				->where('teacher_id', auth()->id())
				->whereNotNull('archived_at')
				->orderBy('name')
				->get()
		]);
	}

	public function restore(string $slug)
	{
		ClassRoom::mine(auth()->user())
			->where('teacher_id', auth()->id())
			->where('slug', $slug)->update([
				'archived_at' => null
			]);

		return redirect()->route('class-rooms.archived');
	}
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/class-rooms/posts/create.blade.php
<x-app-layout>
	<x-slot name="header">Create Class Room Post</x-slot>

	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<form action="{{ route('class-rooms.posts.store', $classRoom->slug) }}" method="post" enctype="multipart/form-data" autocomplete="off">
					@csrf

					<div class="card-header">
						<h4>Class Room's Post Form</h4>
					</div>
					<div class="card-body">
						<div class="form-group">
							<label>Title</label>
							<input id="title" type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" onkeyup="$('#slug').val(slugify($(this).val()))">
							@error('title') <div class="invalid-feedback">{{ $message }}</div> @enderror
						</div>
						<div class="form-group">
							<label>Slug</label>
							<input id="slug" type="text" name="slug" class="form-control @error('slug') is-invalid @enderror" value="{{ old('slug') }}">
							@error('slug') <div class="invalid-feedback">{{ $message }}</div> @enderror
							<div class="text-small text-muted">Used to identify the class room. It must be unique.</div>
						</div>
						<div class="form-group mb-0">
							<label>Content</label>
							<textarea name="content" class="form-control summernote @error('content') is-invalid @enderror" rows="10">{{ old('content') }}</textarea>
							@error('content') <div class="invalid-feedback">{{ $message }}</div> @enderror
						</div>
					</div>
					<div class="card-footer text-right">
						<button class="btn btn-icon icon-left btn-primary"><i class="fas fa-save"></i> Save</button>
						<a href="{{ route('dashboard') }}" class="btn btn-icon icon-left btn-secondary"><i class="fas fa-chevron-left"></i> Kembali</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	@push('css-libraries')
		<link rel="stylesheet" href="{{ asset('assets/modules/summernote/summernote-bs4.css') }}">
	@endpush

	@push('js-libraries')
		<script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
	@endpush
</x-app-layout>

resources/views/class-rooms/posts/detail.blade.php
<x-app-layout>
	<x-slot name="header">{{ $post->title }}</x-slot>
	<div class="row">
		<div class="col-lg-12">
			@if(auth()->user()->roleIs('teacher'))
			<div class="d-flex justify-content-end mb-2">
				<a href="{{ route('class-rooms.posts.edit', [$classRoom->slug, $post->slug]) }}" class="btn btn-warning btn-icon icon-left"><i class="fas fa-edit"></i> Edit Post</a>
				<button type="button" class="btn btn-danger btn-icon icon-left ml-2" data-confirm="Delete Post?|You are about to delete a post. This action can not be undone. Do you still want to continue?" data-confirm-yes="$('#deletePost').submit();"><i class="fas fa-trash"></i> Delete Post</button>
				<form id="deletePost" action="{{ route('class-rooms.posts.delete', [$classRoom->slug, $post->slug]) }}" method="post" class="hidden">@csrf @method('delete')</form>
			</div>
			@endif
			<article class="card">
				<div class="card-body">
					<div class="mb-2 font-weight-bold text-small"><a href="{{ route('class-rooms.posts.index', $classRoom->slug) }}">◀ Back</a> &bull; <a>{{ $classRoom->teacher->name }}</a> &bull; <a>{{ $post->published_at->diffForHumans() }}</a></div>
					<div>{!! $post->content !!}</div>
				</div>
			</article>
		</div>
	</div>
</x-app-layout>

resources/views/class-rooms/posts/edit.blade.php
<x-app-layout>
	<x-slot name="header">Edit Class Room Post</x-slot>

	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<form action="{{ route('class-rooms.posts.update', [$classRoom->slug, $post->slug]) }}" method="post" enctype="multipart/form-data" autocomplete="off">
					@csrf

					<div class="card-header">
						<h4>Class Room's Post Form</h4>
					</div>
					<div class="card-body">
						<div class="form-group">
							<label>Title</label>
							<input id="title" type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') ?? $post->title }}" onkeyup="$('#slug').val(slugify($(this).val()))">
							@error('title') <div class="invalid-feedback">{{ $message }}</div> @enderror
						</div>
						<div class="form-group">
							<label>Slug</label>
							<input id="slug" type="text" name="slug" class="form-control @error('slug') is-invalid @enderror" value="{{ old('slug') ?? $post->slug }}">
							@error('slug') <div class="invalid-feedback">{{ $message }}</div> @enderror
							<div class="text-small text-muted">Used to identify the class room. It must be unique.</div>
						</div>
						<div class="form-group mb-0">
							<label>Content</label>
							<textarea name="content" class="form-control summernote @error('content') is-invalid @enderror" rows="10">{{ old('content') ?? $post->content }}</textarea>
							@error('content') <div class="invalid-feedback">{{ $message }}</div> @enderror
						</div>
					</div>
					<div class="card-footer text-right">
						<button class="btn btn-icon icon-left btn-primary"><i class="fas fa-save"></i> Save</button>
						<a href="{{ route('dashboard') }}" class="btn btn-icon icon-left btn-secondary"><i class="fas fa-chevron-left"></i> Kembali</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	@push('css-libraries')
		<link rel="stylesheet" href="{{ asset('assets/modules/summernote/summernote-bs4.css') }}">
	@endpush

	@push('js-libraries')
		<script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
	@endpush
</x-app-layout>

resources/views/class-rooms/posts/index.blade.php
<x-app-layout>
	<x-slot name="header">{{ $classRoom->name }} Posts</x-slot>

	<div class="row">
		@foreach($classRoom->posts as $post)
			<div class="col-lg-4 mb-4">
				<article class="article article-style-b h-100">
					<div class="article-details">
						<div class="article-title text-truncate"><h2><a href="{{ route('class-rooms.posts.detail', [$classRoom->slug, $post->slug]) }}">{{ $post->title }}</a></h2></div>
						<div class="text-small article-category">{{ $post->created_at->diffForHumans() }}</div>
						<div>{!! $post->content_preview !!}</div>
					</div>
				</article>
			</div>
		@endforeach
		@if(auth()->user()->roleIs('teacher'))
		<div class="col-lg-4 mb-4">
			<div class="card bg-transparent shadow-none border h-100">
				<div class="card-body d-flex align-items-center justify-content-center">
					<a href="{{ route('class-rooms.posts.create', $classRoom->slug) }}" class="btn btn-secondary btn-icon icon-left"><i class="fas fa-plus"></i> Create New Post</a>
				</div>
			</div>
		</div>
		@endif
	</div>
</x-app-layout>